---
- hosts: localhost
  tasks:
  - name: install boto3
    pip:
     name: boto3
     state: present
  - name:  Launch EC2
    ec2_group:
     aws_access_key: AKIAJ5KDTY5V2T2ALTYA
     aws_secret_key: 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
     name: Script_Ec2_Group_new_1
     description: Allow  22
     region: eu-west-1
     rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: 22
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
     rules_egress:
       - proto: all
         cidr_ip: 0.0.0.0/0
  - name: Launch Ec2
    ec2:
     aws_access_key: AKIAJ5KDTY5V2T2ALTYA
     aws_secret_key: 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
     image: ami-9cbe9be5
     key_name: Chef
     count: 1
     instance_type: t2.micro
     wait: yes
     region: eu-west-1
     instance_tags:
      Name: demo
      Owner: Raja
     monitoring: no
     group: Script_Ec2_Group
    register: ec2_out
  - name: Wait for ssh
    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: "{{ ec2_out.instances }}"
